server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb?characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: 184429
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL

  mvc:
    view:
      prefix: classpath:/static/

logging:
  config: classpath:log4j2.xml
